config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
  get 'pages/index'
  get 'users/profile'
  get 'users/configuration'
  resources :searches
  resources :services do
    resources :reviews, only: [:create, :destroy]
    # delete 'delete_image/:photos_id', on: :member, to: 'services#delete_image', as: 'delete_image'
    delete 'delete_image/:photo_id', to:'services#delete_image', as:'delete_image'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"

end

app/models/service.rb
class Service < ApplicationRecord
    belongs_to :user
    has_many :reviews, dependent: :destroy
    has_many :usertags
    has_many :tags, through: :usertags
    has_many_attached :photos
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  authorize_resource
  # load_and_authorize_resource

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @reviews = Review.all
    @review = Review.new
    @users = User.all
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    @service.user = current_user
    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def delete_image
  #   @photo = ActiveStorage::Attachment.find(params[:id])
  #   @photo.purge
  #   redirect_to service_path(@service)
  #   end
    def delete_image
      @service = Service.find(params[:service_id])
      if @service.user == current_user
      begin
        @photo = ActiveStorage::Attachment.find(params[:photo_id])
        @photo.purge
        redirect_to service_path(@service), notice: 'Imagen eliminada con éxito'
      rescue ActiveRecord::RecordNotFound
        redirect_to service_path(@service), alert: 'Error al eliminar la imagen'
      end
    else
      redirect_to service_path(@service), alert: 'Error al eliminar la imagen'
    end
    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :category, :description, :home, photos: [])
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> No se ha podido guardar el servicio</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Categoría %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :Describe_tu_servicio %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :Vas_a_domicilio? %>
    <%= form.check_box :home %>
  </div>

  <div class="field">
    <%= form.label :Fotos %>
    <%= form.file_field :photos, multiple: true  %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/_service.html.erb
<div class='col-md-3 px-3 my-3'>
  <div class="card">
    <!-- <#%= image_tag service.photos, class: 'card-img-top', style: 'height:200px'%> -->
    
    <div class="bd-example">
      <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel"> 
        <% if service.photos.attached?%>
        <% (0..(service.photos.count-1)).each do |i| %>
        <ol class="carousel-indicators">
          <% if i==0%>
          <li data-target="#carouselExampleCaptions" data-slide-to=i class="active"></li>
          <% else %>    
          <li data-target="#carouselExampleCaptions" data-slide-to=i></li>
          <% end %>  
        </ol>
        <% end %>
        <% end %>
        
        
        
        <% if service.photos.attached?%>
        <div class="carousel-inner">
          <% service.photos.each do |photo|%>
          <% if photo == service.photos.first %>
          <div class="carousel-item active">
            <%= image_tag photo, class: "d-block w-100" %>
          </div>
          <% else %>   
          <div class="carousel-item">
            <%= image_tag photo, class: "d-block w-100" %>
          </div>
          <% end %>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
    
    <div class="card-body">
      <h5 class="card-title"><%= service.name %></h5>
      <p class="card-text">Servicio a domicilio: 
        <% if service.home == true %>
        <%= "Si" %>
        <% else %>
        <%= "No" %>
        <% end %>
      </p>
      <p>Categoría: <%= service.category %></p>
      <br>
      <%= service.description %>
      <br>
      <%= link_to 'Ver', service %>
      <% if can?(:edit, service) %>
      <%= link_to '| Editar |', edit_service_path(service) %>
      <% end %>
      <% if can?(:destroy, service) %>
      <%= link_to 'Eliminar', service, method: :delete, data: { confirm: 'Estás segura?' } %>
      <% end %> 
    </div>
    <div class="card-footer">
      <small class="text-muted"><%=service.user.name%></small>
    </div>
    
  </div>
</div>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<div>
  <div class="caja2 text-white">
    <div class="image1 display-1">
      <h2 class="display-4 text1">Servicios</h2>
    </div>
  </div>
</div>
<div class="jumbotron">
  
  <div class="caja1">
    <form action="<%=new_search_path%>">
      <p><strong>Buscar</strong></p>
      <input name="q">
    </form>
  </div>
  
  <div class="container">
    <div class="card-deck" id="services">
      <%= render @services%>
    </div>
    <br>
    
    <script>
      $("[name=q]").keyup(function(event){
        $.ajax({
          url:'<%=new_search_path%>',
          type: 'GET',
          dataType:'script',
          data: {q: $(this).val()}
        })
      });
    </script>
    <div class="caja_profile">
      <%= link_to 'Quiero ofrecer un servicio', new_service_path %>
    </div>
  </div>      
  
</div>

app/views/services/index.js.erb
$("#services").html("<%= j render @services%>");

app/views/services/new.html.erb
<h1>Nuevo Servicio</h1>
<h5>¿Qué ofreces? ¿Haces reparaciones? ¿Preparas unos deliciosos platos? ¿Eres estilista? ¿Además vas a domicilio? Cuéntale a tus posibles clientas!!! </h5>

<%= render 'form', service: @service %>

<%= link_to 'Atrás', services_path %>

app/views/services/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>Nombre:</strong>
    <%= @service.name %>
  </p>
  
  <p>
    <strong>Categoría:</strong>
    <%= @service.category %>
  </p>
  
  <p>
    <strong>Descripción del servicio:</strong>
    <%= @service.description %>
  </p>
  
  <p>
    <strong>Va a domicilio:</strong>
    <% if @service.home == true %>
    <%= "Si" %>
    <% else %>
    <%= "No" %>
    <% end %>
  </p>
  
  
  <p>
    <strong>Fotos:</strong>
    <% if @service.photos.attached? %>
    <br>
    <% @service.photos.each do |photo| %>
    <%= image_tag photo.variant(resize: "200x200") %>
    <br>
    <%= link_to 'Remove', service_delete_image_path(@service, photo), method: :delete, data: { confirm: 'Are you sure?' } %>
    <br>
    <% end %>
    <% end %>
    <!-- <#%= image_tag @service.photos, class: 'card-img-top', style: 'height:200px, weight:200px'%> -->
  </p>
  
  <p>
    <strong>Usuaria:</strong>
    <%= link_to @service.user.name, users_profile_path%>
  </p>
  <div class="py-5 ml-auto">
    <%= link_to  "Quiero contratar este servicio", services_path, class:'btn btn-dark' %>
  </div>
  <%= form_with(model: [@service, Review.new]) do |form| %>
  <% if @review.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
    
    <ul>
      <% @review.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  
  
  <div class="caja_profile">
    <div class="field">
      <%= form.label :Escribe_tu_comentario%>
      <%= form.text_area :comment %>
    </div>
    
    <div class="actions">
      <%= form.submit %>
    </div>
    <% end %>
  </div>
  <br>
  <%@service.reviews.each do |review| %>
  <div id="reviews1">
    <br>
    <div class="caja1">
      <div class="caja_profile">
        <p>Usuario: <%=review.user.name%>, Creado el <%=review.created_at%></p>
      </div>
      <p>Comentario: <%=review.comment %></p>
    </div>
    <%end%>
  </div>
  
  <br>
  
  <%= link_to 'Editar', edit_service_path(@service) %> |
  <%= link_to 'Atrás', services_path %>
</div>