config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
  get 'pages/index'
  get 'users/profile'
  get 'users/configuration'
  resources :searches
  resources :services do
    resources :reviews, only: [:create, :destroy]
    # delete 'delete_image/:photos_id', on: :member, to: 'services#delete_image', as: 'delete_image'
    delete 'delete_image/:photo_id', to:'services#delete_image', as:'delete_image'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sororiservice</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= render 'application/favicon' %>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Fjalla+One|Satisfy&display=swap" rel="stylesheet">  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light">
    <%= link_to 'SORORISERVICE', pages_index_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item, <%= 'active' if current_page?(pages_index_path) %>">
          <%= link_to 'Inicio', pages_index_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Servicios', services_path, class: 'nav-link' %>
        </li>
        
        <li class="nav-item">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Perfil', users_profile_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Configuración', edit_user_registration_path, class: 'nav-link' %>
          </li>
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          <% else %>  
          <%= link_to 'Iniciar sesión', user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Crea una cuenta', new_user_registration_path, class: 'nav-link' %>
        </li>
        <% end %>                           
      </ul>
    </div>
  </nav>
  
  <div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  
  <footer class="page-footer font-small" style="background-color: black">    
    <div class="footer-copyright text-center py-3">© 2019 Copyright: SORORISERVICE</div>
  </footer>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>   